### ISSUE TITLE
DNS server reaching maximum concurrent requests

### ISSUE THREAD

**Issue by sanketpathak** [code-ready/osp4#53] opened 2019-04-05 08:25 UTC
While running crc latest POC(crc_libvirt_nightly-04022019) I was not able to access the console as the network manager reached maximum DNS requests. Please find the logs from the network manager below.

```
Apr 05 13:29:00 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:29:00 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:29:00 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:29:00 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:29:00 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:29:00 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:29:00 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:29:04 localhost.localdomain NetworkManager[31810]: <info>  [155445114>
Apr 05 13:30:45 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:30:55 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:31:05 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:31:15 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:31:25 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:31:35 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:31:45 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:31:55 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:32:05 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:32:15 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:32:25 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:32:35 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:32:45 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:32:55 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:33:05 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:33:15 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
Apr 05 13:33:25 localhost.localdomain dnsmasq[3329]: Maximum number of concurre>
```

**Comment by sanketpathak** [comment] 2019-04-05 08:26
cc: @praveenkumar  @gbraad

**Comment by gbraad** [comment] 2019-04-05 08:31
Duplicate of https://github.com/code-ready/crc/issues/25

**Closed by gbraad** 2019-04-05 08:31 UTC
